### ISSUE TITLE
Annotation does not point to the selected text when multiple comments are added

### ISSUE THREAD

**Issue by srinidhirao** [recogito/recogito-js#44] opened 2021-08-11 14:09 UTC
I'm having an issue with the position of the Annotation popover when I add multiple comments which exceed the length of the page. In the following image, the highlighted text is the one for which annotations are added:

![Annotation_view](https://user-images.githubusercontent.com/9901457/129040361-89ecdf90-489d-4809-88f5-af0f89f638b7.png)

When I add a Recogito annotation for the same, after multiple comments this is how it shows up:

![recogito_error](https://user-images.githubusercontent.com/9901457/129040674-e2d080b2-be2b-4078-bcc5-78a9fb227c27.png)

What I was expecting to see was the behaviour as shown in the online demo put up here:
https://recogito.github.io/recogito-js/

![recogito_demo](https://user-images.githubusercontent.com/9901457/129043379-a48ae698-e860-44cc-ba80-9438665cddcb.png)

 
Here the pointer always points to the selected text and the page itself scrolls (notice the scrollbars on the right side) to reveal the compete annotation thread. 

I inspected the demo app's folder and it appears to be using an old version of Recogito JS (which has just the min.js exported, there is no css export as present in the latest versions). I'm not sure which version it is, but if I check the releases page, its in the format of some initial versions, where in by default it adds comment and tag and there is no plugin widget concept. 

@rsimon 
Can you please help me fix this?

I have hosted my changes here:
https://srinidhirao.github.io/

1. When the page loads, select a text on the last line to add an annotation.
2. Keep adding annotations on the same selected text till the point of time when the height of the widget is exceeds the browser window height.
3. When it exceeds the height of the page, you will notice that the pointer on the widget does not point to the selected text and annotation widget just displays in the center of the page.

**Comment by rsimon** [comment] 2021-08-12 16:13
Ah - good point. Yes, that's actually due to a change for Annotorious, where it's desired behavior. The editor remains attached to the annotation - until it gets pushed out of the window. After that, the position is adjusted so that the editor remains inside the viewport as good as possible. This makes sense for image annotation. But I agree it's awkward behavior for text.

I guess the proper way would be to make this behavior switchable, so that it can stay like it is for Annotorious, but doesn't happen in RecogitoJS. 

The code where the Editor positioning happens is [here](https://github.com/recogito/recogito-client-core/blob/main/src/editor/setPosition.js). Specifically, this is the part where the editor is checked for intersection with the viewport, and pushed upwards:

https://github.com/recogito/recogito-client-core/blob/main/src/editor/setPosition.js#L35-L55

I guess for RecogitoJS, it would be better to disable the parts that are marked as "Test 3" and "Test 4" in the comments.

**Comment by srinidhirao** [comment] 2021-08-13 13:06
Thanks @rsimon  for the pointer. I did comment out the code as you suggested in recogito-client-core and tried. This is how the annotation view showed up:

![final_output](https://user-images.githubusercontent.com/9901457/129360440-86af8f22-a058-46d2-9404-c120c7e8c7ea.png)

The annotation popup went up and the top part got cut off.

Then I commented out all the code all the code that was present in the _setPosition function_

https://github.com/recogito/recogito-client-core/blob/main/src/editor/setPosition.js#L17-L55

I then got the annotation view as I was expecting. I have updated my code here with the latest changes.
https://srinidhirao.github.io/

The annotation view shows up at the bottom and I can scroll the page to view the annotation view in full. Is this something we can do for RecogitoJS but not for Annotorious? if so, how to achieve this differentiation?

**Comment by rsimon** [comment] 2021-08-21 06:41
I think this could be covered with a bit of plumbing. `setPosition` would just need to be extended with an extra boolean argument (maybe `moveIntoView`). This would control whether the tests for re-positioning are done or not.

Then the `Editor` class could get the same argument as a prop. This way you could istantiate the Editor like so:

```jsx
<Editor
  draggable
  moveIntoView

  //... etc.
```

Annotorious could instantiate the editor with `moveIntoView` set, RecogitoJS could leave it out, preventing the auto-position behavior.

**Comment by rsimon** [comment] 2021-09-05 06:18
Hi,

I made this behavior switch-able now. The default is still that the editor will force itself into the visible screen area as good as possible. But you can now disable this when initializing RecogitoJS like so:

```js
var r = Recogito.init({
  content: 'content',
  editorAutoPosition: false // defaults to true
});
```

**Closed** 2021-09-05 06:19 UTC

**Comment by Emmanuel-Edidiong** [comment] 2022-05-24 09:41
Hello @rsimon how can I copy a text before recogito initializes. It doesn't allow me to copy the highlighted text before making a note

**Comment by rsimon** [comment] 2022-05-24 10:46
Hm... this used to work. Looks like its a regression bug. Would you mind creating a separate issue for this, so it gets more visibility?
